version: "3"

networks:
  default:
    driver: bridge
  pocker:
    external:
      name: pocker-proxy

volumes:
  data-sql:

services:
  php:
    build: ./docker/php
    environment:
      PHP_UID: ${PHP_UID:-1000}
      PHP_GID: ${PHP_GID:-1000}
      DOCKER_IP: ${DOCKER_IP}
    depends_on:
      - sql
    volumes:
      - '~/.composer/:/home/httpd/.composer'
      - './:/home/httpd/optical/audio'
      - '~/.ssh/:/home/httpd/.ssh/'
      - '${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}'
  web:
    image: nginx:1.19
    depends_on:
      - php
    environment:
      VIRTUAL_HOST: opticalaudio.symfony.*
      HTTPS_METHOD: noredirect
    volumes:
      - './docker/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './:/home/httpd/optical/audio:ro'
    networks:
      - pocker
      - default
  sql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: sasql
      MYSQL_DATABASE: admin
    volumes:
      - 'data-sql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    depends_on:
      - sql
    environment:
      PMA_HOST: sql
      PMA_ABSOLUTE_URI: http://phpmyadmin.opticalcenter.dev.test
      VIRTUAL_HOST: phpmyadmin.opticalcenter.*
      HTTPS_METHOD: noredirect
    networks:
      - pocker
      - default
